### PR TITLE
Adding Things Stack integration to SD1001, LORIOT needs checking.

### PR DESCRIPTION
**Pull request by dhakke**

### CODE REVIEW

**Comment by artem-barysh-dev** [comment]
@dhakke please change the PR branch from main to feature

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin  you don't need to change the branch anymore, I did

**Comment by yobiiq-fostin** [comment]
@artem-barysh-dev there are conflicts between my last commits and your changes in the ChirpStack downlink.

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin Today, I made adjustments to the converter for the downlink along with the corresponding payload and result, as there were errors that caused validation to fail. We can resolve this issue as follows: since you have already made a PR, it would be great if you could handle these conflicts on your side, using your version of the changes.

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin Okay, I see the conflicts are already resolved, so I’m starting to review your integrations.

**Comment by yobiiq-fostin** [comment]
@artem-barysh-dev thanks, you can also check the Loriot downlink issue.

**Pull request merged**
