### PR TITLE
Updated ChirpStack integration for SD1001

### PR DESCRIPTION
**Pull request by artem-barysh-dev**

### CODE REVIEW

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin 

I have modified the integration with ChirpStack LNS:

    1) Keys that are common across all integrations are now named consistently across them. For example, we use eui in all integrations because eui is shared across all of them, even though some systems might name it differently, such as EUI for Loriot or devEui for ChirpStack.

  2) I have also added a data decoding function in the uplink converters. For instance, values like powerEvent need to be derived by decoding your data.

  3)  We have also started using the includeGatewayInfo key in the metadata within the uplink converters. By default, it is set to false, but if the user wants to include it in the telemetry, they can set it to true.

  4) Additionally, I removed values that were duplicated in both attributes and telemetry. For instance, values that result from data decoding are now placed only in telemetry.

  5) We no longer use toFlatMap() due to its complexity. Instead, we now use a different approach. For example, if you have data = {"cat": "hungry", "cat_1": "very hungry"} and want the output to be {"cat": "hungry"}, previously, with toFlatMap(), you would need to write result = toFlatMap(data, ["cat_1"]), specifying keys to exclude from the final result. Now, you only need to write result.cat = data.cat, explicitly defining the key name and its value.

You can review the examples of payloads and results, and if there are any keys you’d like to add to the final result, please let us know.

**Comment by yobiiq-fostin** [comment]
@artem-barysh-dev Thanks for the clarification.
Are the other metadata keys (**port** for Loriot, **fPort** for ChirpStack) still unchanged?

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin we use fPort for all integrations, I will change it to fPort in other integrations as well.

**Comment by artem-barysh-dev** [comment]
@yobiiq-fostin 

I reviewed payload examples for other integrations, and one issue arose with the payload for Loriot. Unfortunately, it does not contain **data** encoded in hexadecimal that can be decoded in our converter. Could you provide an example of an uplink payload where this data field is included? Below, I’ve attached an example from the Loriot documentation that includes the data field.

{
   "cmd"          : "txd",
   "EUI"          : "0102030405060708",
   "seqdn"        : 1,
   "seqq"         : 2,
   "ts"           : 1690901930921,
   "gweui"        : "1020304050607080",
   "freq"         : 867500000,
   "sf"           : 12,
   "codr"         : "4/5",
   "toa"          : 1155,
   "msgType"      : "User DL",
   "time"         : 1690901930921,
   "ackRequested" : false,
   "port"         : 1,
   "data"         : "0102AABB"
}

**Comment by yobiiq-fostin** [comment]
@artem-barysh-dev 
I'm updating our converters by adding the decoder internally, so they will function regardless of whether there's a codec on the LNS. However, I noticed that the ChirpStack downlink isn't working with the **eui** metadata.
Will this be supported in the next release of TB?

I will also correct the uplink payloads of each integration.

**Comment by artem-barysh-dev** [comment]
Hello, please create a pull request for your changes to the feature branch once you’ve completed them. As for eui, it is planned for future releases. For now, we can work around it by checking if eui exists; if not, we’ll use devEui. Please provide the code, and I will handle these changes on my end. Thank you!

**Pull request merged**
