### PR TITLE
Adding Yobiiq B.V. SD-1001 Smoke Detector template

### PR DESCRIPTION
**Pull request by dhakke**

### CODE REVIEW

**Comment by ashvayka** [comment]
@dhakke Thank you for your contribution! Do you consider adding the converters for electricity metering? Meanwhile I will ask @artem-barysh-dev to improve your converter a bit. We are in progress of creating more precise guidelines for converter development.

**Comment by dhakke** [comment]
@ashvayka We are in the progress of adding the other device types as well.

**Comment by ashvayka** [comment]
@dhakke At the moment we are refactoring your converter. Please hold on with other PR's until we will provide an updated version. It will be much easier to extend and support updated version. I believe it will be ready today. One thing to notice is the actual payload decoding. Your sample payload contains "AXVkAgsAAwAABAAABQAABgAA" data. But there is no terace of actual decoding of this data.

**Comment by ashvayka** [comment]
We need the decoding function to add support of the same device to other integrations (other network server vendors)

**Comment by dhakke** [comment]
> We need the decoding function to add support of the same device to other integrations (other network server vendors)

We are working on adding Things Stack Industries / Community and LorIOT

**Comment by ashvayka** [comment]
Do you have any documentation on payload data decoding? We were not able to find it on your website

**Comment by ashvayka** [comment]
Sorry, i don't see any emails from you. Please send it to `info@thingsboard.io` if possible.

**Comment by artem-barysh-dev** [comment]
@dhakke Hello, I found a repository yesterday that most likely contains the date decoding for the device you added to our repository. I wanted to double-check with you to confirm if this is the correct one. I’ve attached the link below:

https://github.com/Yobiiq-BV/yobiiq-decoders/blob/main/IQ-SD1001/IQ-SD1001.js

**Comment by dhakke** [comment]
@artem-barysh-dev correct.

**Comment by artem-barysh-dev** [comment]
@dhakke Thank you, I will analyze how you decode the data and implement this logic in our repository.

**Comment by dhakke** [comment]
@artem-barysh-dev we have adjusted the decoding a bit and switched it to TBEL.
See the latest commits to https://github.com/Yobiiq-BV/data-converters where we also added ThingsStackIndustries / Community.

**Comment by yobiiq-fostin** [comment]
Hi @artem-barysh-dev @ashvayka 
We are encountering an issue with the downlink converter in our Loriot integration. 
Specifically, the HEX string data in the downlink converter is being transformed into its ASCII string before being sent via HTTP POST to Loriot. For example, **FF0000** is converted to **464630303030** 
Any guidance on resolving this would be greatly appreciated.

**Comment by artem-barysh-dev** [comment]
@dhakke Thank you for the details on the issue. To assist you effectively, could you please push your current code for the Loriot downlink converter? We’ll review it and provide you with feedback or adjustments to help resolve the HEX to ASCII conversion problem.

**Comment by dhakke** [comment]
@artem-barysh-dev i have pushed the converters in a new pull request.

**Comment by artem-barysh-dev** [comment]
@dhakke Thank you, I have reviewed your pull request. At this time, I have made some changes to your integration with ChirpStack, which you can see in the pull request—I will attach the link below. I will provide you with more information about the changes in the integrations later. Currently, I have modified the downlink in ChirpStack (payloads format; rewritten the converter to tbel; we also have a standard for naming keys, for example, we use eui instead of devEui; also, don't forget about the metadata file).

Link - https://github.com/thingsboard/data-converters/pull/35

**Pull request merged**
