### PR TITLE
Add Decentlab devices

### PR DESCRIPTION
**Pull request by decentlab**
Added the following Decentlab devices for Chirpstack, ThingsStackCommunity, LORIOT, ThingPark and ThingParkEnterprise:

- DL-5TM
- DL-ALB
- DL-ATM22
- DL-ATM41
- DL-BLG
- DL-CTD10
- DL-CWS
- DL-CWS2
- DL-DLR2-002
- DL-DLR2-003
- DL-DLR2-004
- DL-DLR2-005
- DL-DLR2-006
- DL-DLR2-008
- DL-DLR2-009
- DL-DLR2-010
- DL-DLR2-011
- DL-DLR2-012
- DL-DS18
- DL-DWS
- DL-GMM
- DL-IAM
- DL-IFD
- DL-ILT
- DL-ISD
- DL-ISF
- DL-ITST
- DL-KL66
- DL-LID
- DL-LP8P
- DL-LPW
- DL-LWS
- DL-MBX
- DL-MES5
- DL-NTU
- DL-OPTOD
- DL-PAR
- DL-PHEHT
- DL-PM
- DL-PR21
- DL-PR26
- DL-PR36
- DL-PR36CTD
- DL-PYR
- DL-RHC
- DL-SDD
- DL-SHT35-001
- DL-SHT35-002
- DL-SMTP
- DL-TBRG
- DL-TP
- DL-TRS11
- DL-TRS12
- DL-TRS21
- DL-WRM
- DL-ZN1
- DL-ZN2

### CODE REVIEW

**Comment by ashvayka** [comment]
Thank you for the PR. It will take some time to review, but we will merge soon.

**Comment by ashvayka** [comment]
it is better to create separate PR for each device, they will be merged faster.  But no need to change anything for this PR. we will review all together

**Comment by artem-barysh-dev** [comment]
@decentlab You have not added the integrations for DL-SHT35-002 to our repository. Do you plan to do so later?

**Comment by decentlab** [comment]
> @decentlab You have not added the integrations for DL-SHT35-002 to our repository. Do you plan to do so later?

Added with https://github.com/thingsboard/data-converters/pull/168. Thank you.

**Comment by artem-barysh-dev** [comment]
@decentlab Thank you.

**Pull request merged**
